name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  username: ${{secrets.DOCKER_HUB_USERNAME}}
  password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login doker hub
      
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/ghaction-api:$(date +%s)
        
        - name: Docker Push
          run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/ghaction-api
