name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}} --password-stdin
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD --password-stdin
        - name: Build the Docker image
        run: docker build . --file Dockerfile --tag diegoamc/ghaction-api:$(date +%s)
        
        - name: Docker Push
          run: docker push ${{secrets.DOCKER_HUB_USER}}/ghaction-api:latest
